Settings menu
Adesii/IndieCure pull request #1
Opened 2023-09-30 20:09 UTC by smaug14

2023-09-30 20:41 UTC, Adesii commented
Looks good. 
tho we should probably have a predefined list of resolutions defined in the script and then only populate the dropdown with resolutions that actually are supported by getting the screen size from the Displayserver 
[using this](https://docs.godotengine.org/en/stable/classes/class_displayserver.html#class-displayserver-method-screen-get-size)

2023-09-30 20:42 UTC, Adesii requested changes

2023-09-30 20:42 UTC, Adesii commented on Scripts/UI/Settings/Settings.gd
> +@onready var resoultion_button: OptionButton = $SettingsContainer/ResolutionContainer/ResolutionSelection
spelling mistake

2023-09-30 21:13 UTC, smaug14 commented on Scripts/UI/Settings/Settings.gd
> +@onready var resoultion_button: OptionButton = $SettingsContainer/ResolutionContainer/ResolutionSelection
Fixed

2023-09-30 21:14 UTC, smaug14 commented
> Looks good. tho we should probably have a predefined list of resolutions defined in the script and then only populate the dropdown with resolutions that actually are supported by getting the screen size from the Displayserver [using this](https://docs.godotengine.org/en/stable/classes/class_displayserver.html#class-displayserver-method-screen-get-size)

Done, should be only using sensible resolutions for windowed mode

2023-09-30 21:15 UTC, smaug14 commented
Also fixed warnings that were shown in debugger

2023-10-01 01:54 UTC, Adesii approved these changes

2023-10-01 01:54 UTC, merged